"""
配置管理 - 包含配置文件和常量
"""

from .config import (
    DEFAULT_DRAFT_PROMPT,
    DEFAULT_REVIEW_PROMPT,
    TARGET_LANGUAGES,
    GUI_CONFIG,
    T1_LANGUAGES,
    T2_LANGUAGES,
    T3_LANGUAGES,
    LANGUAGES_BY_TIER
)

__all__ = [
    'DEFAULT_DRAFT_PROMPT',
    'DEFAULT_REVIEW_PROMPT',
    'TARGET_LANGUAGES',
    'GUI_CONFIG',
    'T1_LANGUAGES',
    'T2_LANGUAGES',
    'T3_LANGUAGES',
    'LANGUAGES_BY_TIER'
]
